#!/usr/bin/env bash

set -e

heroku --version

heroku create {{ cookiecutter.heroku_app_name }}

heroku git:remote -a {{ cookiecutter.heroku_app_name }}

heroku buildpacks:add hashnuke/elixir
heroku buildpacks:add https://github.com/gjaldon/heroku-buildpack-phoenix-static.git

heroku addons:create heroku-postgresql:hobby-dev

heroku pg:backups:schedule --at '0:00 America/New_York'


git push heroku master
